name: Farm_Plugin
version: '${version}'

main: com.korensurge.farmPlugin.FarmPlugin
api-version: '1.21.11'
load: POSTWORLD

commands:
  farmplugin:
    description: Enable or Disable FarmPlugin features for a player.
    usage: /farmplugin <feature> <player> <true|false>
    permission: farmplugin.admin
    aliases: [fp, farm]
  infinitechest:
    description: Marks the targeted chest as an infinite item source.
    permission: farmplugin.admin
    usage: /infinitechest <true|false>

permissions:
  farmplugin.admin:
    description: Allows using plugin management commands
    default: false
  farmplugin.bountifulyield:
    description: Allows player to use custom crop harvest yield mechanics.
    default: true
  farmplugin.preventtrample:
    description: Prevents farmland from being trampled when stepped on.
    default: true